# -*- coding: utf-8 -*-
"""IntegracaoDados.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19TD_1YTgFUCvlBvdHlezaWZuUiRlx9sz
"""

import pyspark
from pyspark.sql import SparkSession
from pyspark.sql.functions import *
from pyspark.sql.types import *
from google.colab import drive
drive.mount('/content/drive')

spark = SparkSession.builder.getOrCreate()

pedidos = spark.read.option('header','True').csv('drive/MyDrive/Arquivos_csv/pedidos.csv')
produtos = spark.read.option('header','True').csv('drive/MyDrive/Arquivos_csv/produtos.csv')
clientes = spark.read.option('header','True').csv('drive/MyDrive/Arquivos_csv/clientes.csv')
itens_pedido = spark.read.option('header','True').csv('drive/MyDrive/Arquivos_csv/itens_pedido.csv')

join_pedidos_produtos = pedidos.join(clientes,on = 'id_cliente',how = 'inner')

join_pedidos_produtos.show(5)
pedidos.show(5)
clientes.show(5)

join_pedidos_cancelados_df = pedidos.filter(col('status_pedido') == 'canceled').join(clientes,on = 'id_cliente',how = 'inner')

join_pedidos_cancelados_df.show(5)

pedidos_concat_df = pedidos.withColumn('Id_pedido_cliente',concat(col('id_pedido'),lit('-'),col('id_cliente')))
colunas = pedidos_concat_df.columns
print(colunas)

colunas.remove('Id_pedido_cliente')
colunas.insert(0,'Id_pedido_cliente')

pedidos_concat_df = pedidos_concat_df.select(colunas)
pedidos_concat_df.show(5)

join_pedidos_cancelados_df.write.mode('overwrite').option('header','True').parquet('drive/MyDrive/Spark/itens_pedidos_cancelados.parquet')

spark.stop()